<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>287a11ee-5d7e-4285-a0ee-37d7d56456f3</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Keycloak.Authentication" Version="13.4.6-preview.1.26319.6" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.11" />
    <PackageReference Include="VaultSharp" Version="1.17.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PAS.Applications\PAS.Application.csproj" />
    <ProjectReference Include="..\PAS.Infrastructure\PAS.Infrastructure.csproj" />
    <ProjectReference Include="..\PAS.ServiceDefaults\PAS.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
