// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS.Infrastructure.Persistence;

#nullable disable

namespace PAS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    partial class AssetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAS.Domain.Funds.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Funds", (string)null);
                });

            modelBuilder.Entity("PAS.Domain.Funds.Fund", b =>
                {
                    b.OwnsOne("PAS.Domain.Funds.ValueObjects.Currency", "Currency", b1 =>
                        {
                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("FundId");

                            b1.ToTable("Funds");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.OwnsOne("PAS.Domain.Funds.ValueObjects.Isin", "Isin", b1 =>
                        {
                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("Isin");

                            b1.HasKey("FundId");

                            b1.ToTable("Funds");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.OwnsMany("PAS.Domain.Funds.ValueObjects.Nav", "Navs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.HasKey("Id");

                            b1.HasIndex("FundId");

                            b1.ToTable("FundNavs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.Navigation("Currency")
                        .IsRequired();

                    b.Navigation("Isin")
                        .IsRequired();

                    b.Navigation("Navs");
                });
#pragma warning restore 612, 618
        }
    }
}
